---
title: "NBA_graphs"
output: html_document
date: "2026-02-24"
---
```{r, echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


```{r}
library(pxR)
library(MASS)
library(highcharter) 
library(fpp3)
library(RColorBrewer)
library(openxlsx)  
library(leaflet)  
library(geojsonio)
library(plotly)
library(ggplot2)
library(tidyverse)
```
```{r}
# Cálculo de la transformación de Yeo–Johnson a partir de un vector y un valor de lambda 
yeo.johnson <- function(y, lambda) {
  y_t <- numeric(length(y))
  
  # Para y >= 0
  pos_idx <- which(y >= 0)
  if (lambda == 0) {
    y_t[pos_idx] <- log(y[pos_idx] + 1)
  } else {
    y_t[pos_idx] <- ((y[pos_idx] + 1)^lambda - 1) / lambda
  }
  
  # Para y < 0
  neg_idx <- which(y < 0)
  if (lambda == 2) {
    y_t[neg_idx] <- -log(-y[neg_idx] + 1)
  } else {
    y_t[neg_idx] <- -(((-y[neg_idx] + 1)^(2 - lambda) - 1) / (2 - lambda))
  }
  
  return(y_t)
}

# Estimación óptima de lambda para la transformación de Yeo–Johnson a un vector y para el R2 de la regresión lineal con un vector x sea máximo 
optimize.yeojohnson.R2 <- function(x, y, lambda_range = c(-1, 1.9)) {
 
  # Función objetivo: R² negativo (porque optimize minimiza)
  r2_neg <- function(lambda) {
    y_t <- yeo.johnson(y, lambda)
    modelo <- lm(y_t ~ x)
    return(-summary(modelo)$r.squared)  # queremos maximizar R²
  }
  
  # Optimización de lambda
  opt <- optimize(r2_neg, interval = lambda_range)
  
  # Se retorna el valor óptimo de lambda 
  return(opt$minimum)
}
```


```{r}
tidyData <- read_csv("tidyData.csv") %>% as_tibble()
untidyData <- read_csv("untidyData.csv") %>% as_tibble()
```

```{r, echo=FALSE, }
top_redraft <- untidyData %>%
  filter(year == 2018) %>% 
  distinct(player, .keep_all = TRUE) %>%
  arrange(newPick)

hchart(top_redraft, "scatter", hcaes(x = as.numeric(overall_pick), y = newPick, group = rank)) %>%
  hc_title(text = "Re-Draft 2018") %>%
  hc_xAxis(title = list(text = "Pick Original")) %>%
  hc_yAxis(title = list(text = "Nuevo Pick (Basado en Performance)"), reversed = TRUE) %>%
  hc_tooltip(pointFormat = "<b>{point.player}</b><br>Pick Original: {point.x}<br>Nuevo Pick: {point.y}<br>Diferencia: {point.pickDifference}") %>%
  hc_add_theme(hc_theme_smpl())
```

```{r}
plot_ly(tidyData %>% distinct(player, .keep_all = TRUE), 
        x = ~team, color = ~rank, type = "histogram") %>%
  layout(barmode = "stack",
         title = "Composición de Talento Drafteado por Equipo",
         xaxis = list(title = "Equipo"),
         yaxis = list(title = "Cantidad de Jugadores"))
```


```{r}
df_heat <- tidyData %>%
  filter(year == "2016", rank %in% c("Generational", "SuperStar", "Star", "Elite")) %>%
  group_by(indicator) %>%
  mutate(normValue = ((value - min(value)) / (max(value) - min(value)))) %>%
  ungroup() %>%
  group_by(player, indicator) %>%
  summarise(avg_norm = mean(normValue))

hchart(df_heat, "heatmap", hcaes(x = indicator, y = player, value = avg_norm)) %>%
  hc_colorAxis(stops = color_stops(10, rev(brewer.pal(10, "RdYlGn")))) %>%
  hc_title(text = "Heatmap de Atributos: Elite del Draft") %>%
  hc_tooltip(formatter = JS("function(){ return 'Jugador: ' + this.series.yAxis.categories[this.point.y] + '<br>Atributo: ' + this.series.xAxis.categories[this.point.x] + '<br>Valor Norm: ' + Math.round(this.point.value * 100)/100; }"))
```

```{r}
df_college <- untidyData %>%
  distinct(player, .keep_all = TRUE) %>%
  group_by(college) %>%
  summarise(n = n(), performance = mean(overall_performance)) %>%
  filter(n > 5)

hchart(df_college, "treemap", hcaes(x = college, value = n, color = performance)) %>%
  hc_title(text = "Fábricas de Talento: Jugadores por Universidad") %>%
  hc_tooltip(pointFormat = "Universidad: {point.name}<br>Jugadores: {point.value}<br>Rating Promedio: {point.colorValue:.2f}")
```
`