---
title: "NBAProject"
output:
  flexdashboard::flex_dashboard:
    vertical_layout: fill
runtime: shiny
---

```{r global, include=FALSE}
library(pxR)
library(MASS)
library(shinydashboard)
library(datasets)
library(highcharter) 
library(fpp3)
library(RColorBrewer)
library(openxlsx)  
library(leaflet)  
library(geojsonio)
library(plotly)
library(ggplot2)
library(tidyverse)
library(splines)
```



```{r}
# asociamos funciones a determinadas librerías para evitar posibles errores 
select <- dplyr::select
mutate <- dplyr::mutate
filter <- dplyr::filter
group_by <- dplyr::group_by
summarise <- dplyr::summarise
selectInput <- shiny::selectInput
```


```{r}
# Cálculo de la transformación de Yeo–Johnson a partir de un vector y un valor de lambda 
yeo.johnson <- function(y, lambda) {
  y_t <- numeric(length(y))
  
  # Para y >= 0
  pos_idx <- which(y >= 0)
  if (lambda == 0) {
    y_t[pos_idx] <- log(y[pos_idx] + 1)
  } else {
    y_t[pos_idx] <- ((y[pos_idx] + 1)^lambda - 1) / lambda
  }
  
  # Para y < 0
  neg_idx <- which(y < 0)
  if (lambda == 2) {
    y_t[neg_idx] <- -log(-y[neg_idx] + 1)
  } else {
    y_t[neg_idx] <- -(((-y[neg_idx] + 1)^(2 - lambda) - 1) / (2 - lambda))
  }
  
  return(y_t)
}

# Estimación óptima de lambda para la transformación de Yeo–Johnson a un vector y para el R2 de la regresión lineal con un vector x sea máximo 
optimize.yeojohnson.R2 <- function(x, y, lambda_range = c(-1, 1.9)) {
 
  # Función objetivo: R² negativo (porque optimize minimiza)
  r2_neg <- function(lambda) {
    y_t <- yeo.johnson(y, lambda)
    modelo <- lm(y_t ~ x)
    return(-summary(modelo)$r.squared)  # queremos maximizar R²
  }
  
  # Optimización de lambda
  opt <- optimize(r2_neg, interval = lambda_range)
  
  # Se retorna el valor óptimo de lambda 
  return(opt$minimum)
}

```


```{r}
ParetoValue <- function(v, ParetoSignificancia){
  x <- sort(v, decreasing = TRUE)
  return(x[which(cumsum(x) >= ParetoSignificancia * sum(x))[1]])
}
```



```{r}
rawData <- readr::read_csv('nbaplayersdraft.csv')
```

```{r}
data <- rawData %>% 
  select(-id, -rank) %>%
  mutate(year = as.character(year),
         overall_pick = as.character(overall_pick)
         ) %>%
  replace_na(list(college = "Didn't play College")) %>%
  mutate_if(is.numeric, ~replace_na(., 0)) %>%
  pivot_longer(years_active:value_over_replacement, names_to = 'indicator', values_to = 'value')
```

```{r}
data <- data %>% group_by(indicator) %>%
  mutate(normValue = ((value - min(value)) / (max(value) - min(value)))) %>%
  ungroup()
```


```{r}
categories <- c("Generational", "SuperStar", "Star", "Elite", "Starter", "Solid", "Role", "Rotation", "Deep")

fields <- c("year", "overall_pick", "team" , "player", "college")

data_fields <- data %>% filter(!indicator %in% fields)

player_scores <- data_fields %>%
  filter(!indicator %in% c("points", "total_rebounds", "assists")) %>%
  mutate(
    weighted_value = case_when(
      indicator %in% c("value_over_replacement", "box_plus_minus", "win_shares", "win_shares_per_48_minutes") ~ normValue * 3,
      indicator %in% c("points_per_game", "average_total_rebounds", "average_assists") ~ normValue * 2.5,
      indicator %in% c("field_goal_percentage", "3_point_percentage", "free_throw_percentage") ~ normValue * 1.5,
      indicator %in% c("years_active", "games", "minutes_played", "average_minutes_played") ~ normValue * 1.25,
      TRUE ~ normValue
    )
  ) %>%
  group_by(player, year, overall_pick) %>%
  summarise(
    overall_performance = sum(weighted_value),
  ) %>% ungroup()

baremo <- quantile(player_scores$overall_performance, probs = c(0.15, 0.30, 0.50, 0.65, 0.78, 0.88, 0.96, 0.99))

player_success <- player_scores %>%
 mutate(
    rank = case_when(
      overall_performance >= baremo[8] ~ "Generational",
      overall_performance >= baremo[7] ~ "SuperStar",
      overall_performance >= baremo[6] ~ "Star",
      overall_performance >= baremo[5] ~ "Elite",
      overall_performance >= baremo[4] ~ "Starter",
      overall_performance >= baremo[3] ~ "Solid",
      overall_performance >= baremo[2] ~ "Role",
      overall_performance >= baremo[1] ~ "Rotation",
      TRUE ~ "Deep"
    ),
    rank = factor(rank, levels = categories, ordered = TRUE)
  ) %>% select(-overall_pick, -year)
```


```{r}
dataPerformance <- data_fields %>% left_join(player_success, by = "player") %>%
  select(year, overall_pick, rank, team, player, college, indicator, value, overall_performance)
```


```{r}
reDraft <- dataPerformance %>%
  group_by(year, player) %>%
  summarise(overall_performance = mean(overall_performance)) %>%
  ungroup() %>%
  group_by(year) %>%
  arrange(year, desc(overall_performance)) %>%
  mutate(newPick = row_number()) %>%
  filter(newPick <= 60) %>%
  ungroup() %>%
  select(-year, -overall_performance)
```

```{r}
dataReDraft <- dataPerformance %>% left_join(reDraft, by = "player") %>%
  mutate(pickDifference = as.numeric(overall_pick) - newPick) %>%
  relocate(c(newPick, pickDifference), .after = overall_pick)
```


```{r}
picksAverage <- dataPerformance %>% group_by(overall_pick) %>%
  mutate(overall_pick = as.numeric(overall_pick)) %>%
  summarise(observed_perf = mean(overall_performance))

spline_model <- lm(observed_perf ~ ns(overall_pick, knots = c(5, 14, 30, 44), Boundary.knots = c(1,60)), data = picksAverage)

ideal_curve_spline <- data.frame(overall_pick = 1:60)
ideal_curve_spline$expected_perf <- predict(spline_model, newdata = ideal_curve_spline)
```

```{r}
picksAverage <- picksAverage %>% left_join(ideal_curve_spline, by = "overall_pick")
```

```{r}
picksAverage <- picksAverage %>% mutate(overall_pick = as.character(overall_pick))

```

```{r}
tidyData <- dataReDraft %>% left_join(picksAverage, by = "overall_pick") %>%
  mutate(pick_perf_difference = observed_perf - expected_perf)

base <- tidyData %>%
  select(-overall_performance, -observed_perf, -expected_perf, -pick_perf_difference)

newMetrics <- tidyData %>%
  select(year, overall_pick, newPick, pickDifference, rank, team, player, college, 
         overall_performance, observed_perf, expected_perf, pick_perf_difference) %>%
  distinct()
tidyMetrics <- newMetrics %>%
  pivot_longer(
    cols = c(overall_performance, observed_perf, expected_perf, pick_perf_difference),
    names_to = "indicator",
    values_to = "value"
  )

temptidyData <- bind_rows(base, tidyMetrics) %>% arrange(year, player, indicator)
```

```{r}
unique(tidyData$indicator)
```


```{r}
picksIndicator <- c("observed_perf", "pick_perf_difference", "expected_perf")
tidyData <- temptidyData %>% 
  mutate(unit = case_when(
    indicator %in% picksIndicator ~ "Selection",
    TRUE ~ "Player"
  )) %>%
  relocate(unit, .before = indicator) %>% 
  arrange(year, player, unit, indicator)
```

```{r}
untidyData <- temptidyData %>%
  pivot_wider(
    names_from = indicator,
    values_from = value
  )
```

